#!/usr/bin/env bash
# Authority snapshot of the candidate stack's domain store, independent of any
# subject: every case's accepted snapshot digest, model build digests, frozen
# deliverable export digests, filing receipts and audit chain heads. Taken
# before the soak (pre-soak-authority.json) and again after it by ER-L4, and
# diffed for PERF-015: the pre-soak cases must be byte-for-byte unchanged and
# only the soak's own cases and audit rows may be added. Standard SQL only.
set -euo pipefail
project=${COMPOSE_PROJECT_NAME:-caos-cand-20260903}
psql() { docker compose -p "$project" exec -T db psql -Atq -U caos -d caos -c "$1"; }
printf '{\n  "recorded_at": "%s",\n  "compose_project": "%s",\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$project"
printf '  "counts": %s,\n' "$(psql "SELECT json_build_object('cases', (SELECT count(*) FROM cases), 'sources', (SELECT count(*) FROM sources), 'runs', (SELECT count(*) FROM runs), 'runs_by_status', (SELECT coalesce(json_object_agg(status, n), '{}') FROM (SELECT status, count(*) n FROM runs GROUP BY status) s), 'snapshots', (SELECT count(*) FROM run_snapshots), 'model_builds', (SELECT count(*) FROM model_builds), 'frozen', (SELECT count(*) FROM deliverable_frozen), 'receipts', (SELECT count(*) FROM deliverable_filing_receipts), 'audit_events', (SELECT count(*) FROM audit_events), 'chain_heads', (SELECT count(*) FROM audit_chain_heads), 'run_events', (SELECT count(*) FROM run_events), 'run_nodes_non_terminal', (SELECT count(*) FROM run_nodes WHERE status NOT IN ('succeeded','failed','skipped')), 'freeze_jobs_open', (SELECT count(*) FROM deliverable_freeze_jobs WHERE status IN ('QUEUED','RENDERING')), 'builds_open', (SELECT count(*) FROM model_builds WHERE status IN ('QUEUED','BUILDING')), 'db_connections', (SELECT count(*) FROM pg_stat_activity))")"
printf '  "cases": %s\n}\n' "$(psql "SELECT coalesce(json_agg(row_to_json(c) ORDER BY c.id), '[]') FROM (SELECT cases.id, cases.created_by, cases.accepted_snapshot_id, (SELECT digest FROM run_snapshots WHERE id = cases.accepted_snapshot_id) AS accepted_digest, (SELECT coalesce(json_agg(json_build_object('id', id, 'status', status, 'payload_digest', payload_digest, 'outputs_digest', outputs_digest) ORDER BY seq), '[]') FROM model_builds WHERE case_id = cases.id) AS builds, (SELECT coalesce(json_agg(json_build_object('id', deliverable_id, 'pathway', pathway, 'status', status, 'draft_digest', draft_digest, 'preview_digest', preview_digest, 'exports', exports) ORDER BY seq), '[]') FROM deliverable_frozen WHERE case_id = cases.id) AS frozen, (SELECT coalesce(json_agg(json_build_object('receipt_id', receipt_id, 'receipt_digest', receipt_digest) ORDER BY seq), '[]') FROM deliverable_filing_receipts WHERE case_id = cases.id) AS receipts, (SELECT json_build_object('chain_seq', chain_seq, 'digest', digest) FROM audit_chain_heads WHERE chain_key = cases.id) AS audit_head FROM cases) c")"
