"""Fixed v1 presentation inventory, transcribed from ANALYST_VIEW_COVERAGE.md.

292 ledger rows; empty identifiers bind canonical narrative sections. This is
presentation data only: execution and validation remain registry/compiler owned.
Never change this version's bindings when adding a later saved mapping version.
"""

# module, table identities (alternatives except SCREEN profiles), policy, page
BINDINGS_V1 = [
    ["CP-PARSE",["P1"],"N+T","Evidence / QA"],
    ["CP-PARSE",["P2"],"T","Analysis only"],
    ["CP-PARSE",["P3"],"T","Evidence / QA"],
    ["CP-PARSE",["P4"],"N+T","Evidence / QA"],
    ["CP-PARSE",["P5"],"N+T","Evidence / QA"],
    ["CP-PARSE",["P6"],"T","Analysis only"],
    ["CP-PARSE",["P7"],"N+T","Evidence / QA"],
    ["CP-PARSE",["P8"],"T","Evidence / QA"],
    ["CP-0",["T1"],"N+T","Evidence / QA and readiness"],
    ["CP-0",["T2"],"T","Evidence / QA"],
    ["CP-0",["T3"],"N+T","Evidence / QA"],
    ["CP-0",["T4"],"T","Evidence / QA and readiness"],
    ["CP-0",["T5"],"N+T","Risks / limitations"],
    ["CP-0",["T6"],"T","Evidence / QA"],
    ["CP-0",["T7"],"T","Analysis only"],
    ["CP-0",["T8"],"T","Readiness"],
    ["CP-1",["T4.1"],"T","Evidence / QA"],
    ["CP-1",["T4.2"],"T","Financial performance"],
    ["CP-1",["T4.3"],"N+T","Financial performance"],
    ["CP-1",["T4.4"],"V+T","Financial performance"],
    ["CP-1",["T4.5"],"V+T","Financial performance"],
    ["CP-1",["T4.6"],"V+T","Financial performance"],
    ["CP-1",["T4.7"],"V+T","Financial performance"],
    ["CP-1",["T4.8"],"T","Financial performance"],
    ["CP-1",["T4.9"],"T","Evidence / QA"],
    ["CP-1",["T4.10"],"V+T","Financial performance"],
    ["CP-1",["T4.11"],"N+T","Risks / limitations"],
    ["CP-1",["T4.12"],"N+T","Risks / limitations"],
    ["CP-1",["T4.13"],"T","Analysis only"],
    ["CP-1",["T4.14"],"T","Base / Downside model"],
    ["CP-1",["T4.15"],"V+T","Base / Downside model"],
    ["CP-1",["T4.16"],"V+T","Business / transaction and Base / Downside model"],
    ["CP-1",["T4.17"],"V+T","Earnings quality"],
    ["CP-1",["T4.18"],"V+T","Capital structure and liquidity / covenants"],
    ["CP-1",["T4.19"],"T","Evidence / QA"],
    ["CP-1",["cp1.operating_kpi_schedule"],"V+T","Financial performance and Base / Downside model"],
    ["CP-1",["cp1.cp_model_segment_allocation"],"T","Analysis only"],
    ["CP-1",[],"N+T","Financial performance, Base / Downside model and Evidence / QA"],
    ["CP-1A",["source_classification"],"T","Evidence / QA"],
    ["CP-1A",["transaction_summary"],"N+T","Business / transaction"],
    ["CP-1A",["company_description"],"N+T","Business / transaction"],
    ["CP-1A",["revenue_business_mix"],"V+T","Business / transaction"],
    ["CP-1A",["ownership_register"],"N+T","Business / transaction"],
    ["CP-1A",["operating_model"],"V+T","Business / transaction"],
    ["CP-1A",["cp1a.cp_model_snapshot_fields"],"T","Base / Downside model"],
    ["CP-1A",["events_timeline"],"V+T","Risks / catalysts / monitoring"],
    ["CP-1A",["credit_translation"],"N+T","Credit summary and risks / catalysts"],
    ["CP-1A",["gaps_ledger"],"N+T","Risks / limitations"],
    ["CP-1A",["conflict_log"],"N+T","Risks / limitations"],
    ["CP-1A",["downstream_readiness"],"T","Analysis only"],
    ["CP-1A",["T2D.1"],"T","Evidence / QA"],
    ["CP-1A",["T2D.2"],"N+T","Business / transaction"],
    ["CP-1A",["T2D.3"],"N+T","Risks / catalysts"],
    ["CP-1A",["T2D.4"],"N+T","Risks / catalysts"],
    ["CP-1A",["T2D.5"],"N+T","Business / transaction and risks / catalysts"],
    ["CP-1A",["T2D.6"],"N+T","Business / transaction and capital structure"],
    ["CP-1A",["T2D.7"],"T","Evidence / QA"],
    ["CP-1A",["T2D.8"],"N+T","Risks / catalysts"],
    ["CP-1A",["T2D.9"],"N+T","Risks / catalysts"],
    ["CP-1A",["T2D.10"],"T","Analysis only"],
    ["CP-1A",["T2D.11"],"N+T","Risks / limitations"],
    ["CP-1B",["T4.1"],"T","Evidence / QA"],
    ["CP-1B",["T4.2"],"T","Earnings quality"],
    ["CP-1B",["T4.3"],"N+T","Earnings Update"],
    ["CP-1B",["T4.4"],"V+T","Earnings Update and financial performance"],
    ["CP-1B",["T4.5"],"V+T","Earnings Update and financial performance"],
    ["CP-1B",["T4.6"],"V+T","Earnings Update and earnings quality"],
    ["CP-1B",["T4.7"],"N+T","Earnings Update and risks / catalysts"],
    ["CP-1B",["T4.8"],"V+T","Earnings Update and earnings quality"],
    ["CP-1B",["T4.9"],"N+T","Risks / limitations"],
    ["CP-1B",["T4.10"],"N+T","Monitoring"],
    ["CP-1B",["T4.11"],"N+T","Risks / limitations"],
    ["CP-1B",["T4.12","cp1b.model_comparator_register"],"V+T","Base / Downside model"],
    ["CP-1B",["T4.13","cp1b.model_validation_register"],"T","Evidence / QA"],
    ["CP-1B",["T4.14","cp1b.addback_validation_register"],"T","Earnings quality and Evidence / QA"],
    ["CP-1B",["T4.15","cp1b.model_readiness"],"T","Analysis only"],
    ["CP-1B",["cp1b.cp_model_snapshot_fields"],"T","Base / Downside model"],
    ["CP-1C",["T4.1"],"T","Relative value"],
    ["CP-1C",["T4.2"],"T","Relative value"],
    ["CP-1C",["T4.3"],"V+T","Relative value"],
    ["CP-1C",["T4.4"],"V+T","Relative value"],
    ["CP-1C",["T4.5"],"V+T","Relative value"],
    ["CP-1C",["T4.6"],"V+T","Relative value"],
    ["CP-1C",["T4.7"],"V+T","Relative value and risks / catalysts"],
    ["CP-1C",["T4.8"],"V+T","Relative value"],
    ["CP-1C",["T4.9"],"V+T","Relative value"],
    ["CP-1C",["T4.10"],"V+T","Relative value"],
    ["CP-1C",["T4.11"],"N+T","Risks / limitations"],
    ["CP-1C",["T4.D1"],"T","Evidence / QA"],
    ["CP-1D",["T1D.1"],"T","Earnings quality"],
    ["CP-1D",["T1D.2"],"N+T","Earnings quality"],
    ["CP-1D",["T1D.3"],"N+T","Earnings quality"],
    ["CP-1D",["T1D.4"],"V+T","Earnings quality"],
    ["CP-1D",["T1D.5"],"V+T","Earnings quality"],
    ["CP-1D",["T1D.6"],"V+T","Earnings quality and capital structure"],
    ["CP-1D",["T1D.7"],"N+T","Risks / limitations"],
    ["CP-2",["T2.1"],"T","Evidence / QA"],
    ["CP-2",["T2.7"],"N+T","Credit summary"],
    ["CP-2",["T2.10"],"N+T","Credit summary and risks / catalysts"],
    ["CP-2",["T2.11"],"N+T","Credit summary and risks / catalysts"],
    ["CP-2",["T2.12"],"N+T","Monitoring"],
    ["CP-2",["cp2.cp_model_strengths_weaknesses"],"N+T","Credit summary and Base / Downside model"],
    ["CP-2A",["T2B.1"],"T","Evidence / QA"],
    ["CP-2A",["T2B.2"],"N+T","Base / Downside model"],
    ["CP-2A",["T2B.3"],"N+T","Risks / catalysts"],
    ["CP-2A",["T2B.4"],"V+T","Base / Downside model"],
    ["CP-2A",["T2B.5"],"N+T","Base / Downside model and risks / catalysts"],
    ["CP-2A",["T2B.6"],"V+T","Base / Downside model"],
    ["CP-2A",["T2B.7"],"N+T","Monitoring"],
    ["CP-2A",["T2B.8"],"T","Analysis only"],
    ["CP-2A",["T2B.9"],"N+T","Risks / limitations"],
    ["CP-2A",["T5.1"],"T","Risks / catalysts"],
    ["CP-2A",["T5.2"],"V+T","Risks / catalysts"],
    ["CP-2A",["T5.3"],"N+T","Risks / catalysts"],
    ["CP-2A",["T5.4"],"V+T","Risks / catalysts"],
    ["CP-2A",["T5.5"],"T","Monitoring"],
    ["CP-2A",["T5.6"],"T","Monitoring"],
    ["CP-2A",["T5.7"],"N+T","Risks / limitations"],
    ["CP-2A",["cp2b.cp_model_catalysts"],"V+T","Risks / catalysts and Base / Downside model"],
    ["CP-2E",["T2F.1"],"T","Evidence / QA"],
    ["CP-2E",["T2F.2"],"V+T","Liquidity / refinancing"],
    ["CP-2E",["T2F.3"],"V+T","Liquidity / refinancing"],
    ["CP-2E",["T2F.4"],"V+T","Liquidity / refinancing"],
    ["CP-2E",["T2F.5"],"V+T","Liquidity / refinancing"],
    ["CP-2E",["T2F.6"],"V+T","Risks / catalysts"],
    ["CP-2E",["T2F.7"],"N+T","Risks / catalysts"],
    ["CP-2E",["T2F.8"],"N+T","Risks / catalysts and monitoring"],
    ["CP-2E",["T2F.9"],"N+T","Risks / limitations"],
    ["CP-2E",["T2G.1"],"T","Evidence / QA"],
    ["CP-2E",["T2G.2"],"N+T","Risks / catalysts"],
    ["CP-2E",["T2G.3"],"N+T","Risks / catalysts"],
    ["CP-2E",["T2G.4"],"N+T","Risks / catalysts"],
    ["CP-2E",["T2G.5"],"V+T","Liquidity / refinancing and risks / catalysts"],
    ["CP-2E",["T2G.6"],"N+T","Liquidity / refinancing"],
    ["CP-2E",["T2G.7"],"N+T","Risks / catalysts"],
    ["CP-2E",["T2G.8"],"N+T","Risks / limitations"],
    ["CP-2E",[],"N+T","Risks / catalysts and monitoring"],
    ["CP-2G",["T2H.1"],"T","Evidence / QA"],
    ["CP-2G",["T2H.2"],"V+T","Base / Downside model"],
    ["CP-2G",["T2H.3","cp2g.cp_model_forecast_drivers"],"T","Base / Downside model"],
    ["CP-2G",["T2H.4"],"V+T","Base / Downside model"],
    ["CP-2G",["T2H.5"],"V+T","Base / Downside model and liquidity / refinancing"],
    ["CP-2G",["T2H.6"],"V+T","Base / Downside model and liquidity / refinancing"],
    ["CP-2G",["T2H.7"],"V+T","Base / Downside model and risks / catalysts"],
    ["CP-2G",["T2H.8"],"V+T","Base / Downside model and monitoring"],
    ["CP-2G",["T2H.9"],"N+T","Risks / limitations"],
    ["CP-2H",["T2R.1"],"T","Rating and market risk"],
    ["CP-2H",["T2R.2"],"T","Rating and market risk"],
    ["CP-2H",["T2R.3"],"T","Rating and market risk"],
    ["CP-2H",["T2R.4"],"V+T","Rating and market risk"],
    ["CP-2H",["T2R.5"],"N+T","Rating and market risk"],
    ["CP-2H",["T2R.6"],"V+T","Rating and market risk and risks / catalysts"],
    ["CP-2H",["T2R.7"],"N+T","Risks / limitations"],
    ["CP-2H",["T2R.8"],"N+T","Rating and market risk"],
    ["CP-2H",["T2R.9"],"V+T","Monitoring"],
    ["CP-2H",["T2R.10"],"N+T","Risks / limitations"],
    ["CP-2H",["T3E.1"],"T","Relative value"],
    ["CP-2H",["T3E.2"],"V+T","Relative value"],
    ["CP-2H",["T3E.3"],"V+T","Relative value"],
    ["CP-2H",["T3E.4"],"V+T","Relative value"],
    ["CP-2H",["T3E.5"],"V+T","Relative value and rating and market risk"],
    ["CP-2H",["T3E.6"],"V+T","Relative value"],
    ["CP-2H",["T3E.7"],"N+T","Relative value and rating and market risk"],
    ["CP-2H",["T3E.8"],"V+T","Relative value and risks / catalysts"],
    ["CP-2H",["T3E.9"],"T","Monitoring"],
    ["CP-2H",["T3E.10"],"N+T","Risks / limitations"],
    ["CP-3",["T3.1"],"T","Evidence / QA"],
    ["CP-3",["T3.3"],"V+T","Relative value"],
    ["CP-3",["T3.4"],"T","Relative value"],
    ["CP-3",["T3.5"],"V+T","Relative value"],
    ["CP-3",["T3.6"],"N+T","Relative value"],
    ["CP-3",["T3.7"],"V+T","Relative value"],
    ["CP-3",["T3.9"],"T","Monitoring"],
    ["CP-3",["T3.10"],"N+T","Risks / limitations"],
    ["CP-3",["T3B.1"],"T","Evidence / QA"],
    ["CP-3",["T3B.2"],"V+T","Capital structure"],
    ["CP-3",["T3B.3"],"V+T","Relative value"],
    ["CP-3",["T3B.4"],"N+T","Legal structure and capital structure"],
    ["CP-3",["T3B.5"],"N+T","Legal structure and risks / catalysts"],
    ["CP-3",["T3B.6"],"V+T","Relative value and recovery"],
    ["CP-3",["T3B.7"],"V+T","Relative value"],
    ["CP-3",["T3B.8"],"N+T","Relative value"],
    ["CP-3",["T3B.10"],"T","Monitoring"],
    ["CP-3",["T3B.11"],"N+T","Risks / limitations"],
    ["CP-3",["T3C.1"],"T","Relative value"],
    ["CP-3",["T3C.2"],"N+T","Relative value"],
    ["CP-3",["T3C.3"],"N+T","Relative value"],
    ["CP-3",["T3C.4"],"N+T","Risks / catalysts"],
    ["CP-3",["T3C.5"],"V+T","Relative value"],
    ["CP-3",["T3C.6"],"N+T","Relative value and liquidity / refinancing"],
    ["CP-3",["T3C.7"],"V+T","Relative value and risks / catalysts"],
    ["CP-3",["T3C.8"],"T","Monitoring"],
    ["CP-3",["T3C.9"],"N+T","Risks / limitations"],
    ["CP-4",["T4.2"],"T","Legal structure"],
    ["CP-4",["T4.3"],"N+T","Legal structure and risks / catalysts"],
    ["CP-4",["T4.9"],"N+T","Legal structure and recovery"],
    ["CP-4",["T4.10"],"N+T","Legal structure"],
    ["CP-4",["T4.11"],"T","Legal structure"],
    ["CP-4",["T4.12"],"N+T","Risks / catalysts and monitoring"],
    ["CP-4",["T4.13"],"N+T","Risks / limitations"],
    ["CP-4",[],"N+T","Legal structure and risks / catalysts"],
    ["CP-4",["T4D.1"],"T","Evidence / QA"],
    ["CP-4",["T4D.2"],"N+T","Legal structure"],
    ["CP-4",["T4D.3"],"N+T","Legal structure and capital structure"],
    ["CP-4",["T4D.4"],"N+T","Legal structure and capital structure"],
    ["CP-4",["T4D.5"],"N+T","Legal structure and recovery"],
    ["CP-4",["T4D.6"],"N+T","Legal structure and recovery"],
    ["CP-4",["T4D.7"],"N+T","Legal structure and recovery"],
    ["CP-4",["T4D.8"],"N+T","Risks / limitations"],
    ["CP-4",[],"N+T","Legal structure and risks / catalysts"],
    ["CP-4",["T4F.1"],"T","Legal structure"],
    ["CP-4",["T4F.2"],"N+T","Legal structure and recovery"],
    ["CP-4",["T4F.3"],"N+T","Legal structure and recovery"],
    ["CP-4",["T4F.4"],"N+T","Legal structure and recovery"],
    ["CP-4",["T4F.5"],"N+T","Legal structure and recovery"],
    ["CP-4",["T4F.6"],"N+T","Risks / limitations"],
    ["CP-4",["T4C.2"],"T","Legal structure and liquidity / covenants"],
    ["CP-4",["T4C.3"],"N+T","Liquidity / covenants"],
    ["CP-4",["T4C.4"],"V+T","Liquidity / covenants"],
    ["CP-4",["T4C.5"],"V+T","Liquidity / covenants"],
    ["CP-4",["T4C.6"],"N+T","Legal structure and liquidity / covenants"],
    ["CP-4",["T4C.7"],"V+T","Legal structure and liquidity / covenants"],
    ["CP-4",["T4C.8"],"N+T","Liquidity / covenants and earnings quality"],
    ["CP-4",["T4C.9"],"N+T","Risks / catalysts"],
    ["CP-4",["T4C.11"],"N+T","Liquidity / covenants and monitoring"],
    ["CP-4",["T4C.12"],"N+T","Risks / limitations"],
    ["CP-4",[],"N+T","Legal structure and liquidity / covenants"],
    ["CP-4",[],"N+T","Liquidity / covenants and monitoring"],
    ["CP-4",[],"N+T","Liquidity / covenants and risks / catalysts"],
    ["CP-4C",["T4E.1"],"N+T","Distressed scenarios"],
    ["CP-4C",["T4E.2"],"T","Capital structure and recovery"],
    ["CP-4C",["T4E.3"],"V+T","Distressed scenarios and recovery"],
    ["CP-4C",["T4E.4"],"N+T","Distressed scenarios"],
    ["CP-4C",["T4E.5"],"V+T","Recovery"],
    ["CP-4C",["T4E.6"],"V+T","Recovery"],
    ["CP-4C",["T4E.7"],"V+T","Recovery"],
    ["CP-4C",["T4E.8"],"N+T","Legal structure and recovery"],
    ["CP-4C",["T4E.9"],"V+T","Distressed scenarios and monitoring"],
    ["CP-4C",["T4E.10"],"N+T","Risks / limitations"],
    ["CP-4C",["T3D.1"],"T","Evidence / QA"],
    ["CP-4C",["T3D.2"],"V+T","Liquidity / refinancing"],
    ["CP-4C",["T3D.3"],"N+T","Liquidity / refinancing"],
    ["CP-4C",["T3D.4"],"N+T","Legal structure and distressed scenarios"],
    ["CP-4C",["T3D.5"],"N+T","Distressed scenarios"],
    ["CP-4C",["T3D.6"],"N+T","Distressed scenarios"],
    ["CP-4C",["T3D.7"],"T","Distressed scenarios"],
    ["CP-4C",["T3D.8"],"V+T","Recovery"],
    ["CP-4C",["T3D.9"],"T","Monitoring"],
    ["CP-4C",["T3D.10"],"V+T","Distressed scenarios and recovery"],
    ["CP-4C",["T3D.11"],"N+T","Risks / limitations"],
    ["CP-5",["T5B.1"],"T","Evidence / QA"],
    ["CP-5",["T5B.2"],"N+T","Credit summary and Evidence / QA"],
    ["CP-5",["T5B.3"],"N+T","Evidence / QA"],
    ["CP-5",["T5B.4"],"T","Evidence / QA"],
    ["CP-5",["T5B.5"],"T","Evidence / QA"],
    ["CP-5",["T5B.6"],"N+T","Evidence / QA and risks / limitations"],
    ["CP-5",["T5B.7"],"N+T","Evidence / QA"],
    ["CP-5",["T5B.8"],"N+T","Evidence / QA and risks / limitations"],
    ["CP-5",[],"N+T","Evidence / QA"],
    ["CP-6",["T6A.4"],"N+T","Optional IC challenge"],
    ["CP-6",["T6A.6"],"T","Optional IC challenge"],
    ["CP-6",["T6A.7"],"N+T","Optional IC challenge"],
    ["CP-6",["T6A.11"],"N+T","Optional IC challenge"],
    ["CP-6",[],"N+T","Optional IC challenge"],
    ["CP-6",[],"N+T","Optional IC challenge"],
    ["CP-6",[],"N+T","Optional IC challenge"],
    ["CP-6",[],"N+T","Optional IC challenge"],
    ["CP-6",[],"N+T","Optional IC challenge"],
    ["CP-6",[],"N+T","Optional IC challenge"],
    ["CP-6",[],"N+T","Optional IC challenge"],
    ["CP-6",["T6E.4"],"N+T","Optional IC challenge"],
    ["CP-6",["T6E.6"],"T","Optional IC challenge"],
    ["CP-6",["T6E.7"],"N+T","Optional IC challenge"],
    ["CP-6",["T6E.11"],"N+T","Optional IC challenge"],
    ["CP-6",[],"N+T","Optional IC challenge"],
    ["CP-6",[],"N+T","Optional IC challenge"],
    ["CP-6",[],"N+T","Optional IC challenge"],
    ["CP-6",[],"N+T","Optional IC challenge"],
    ["CP-6",[],"N+T","Optional IC challenge"],
    ["CP-6",[],"N+T","Optional IC challenge"],
    ["CP-6",[],"N+T","Optional IC challenge"],
    ["CP-DR",[],"T","Deep Research scope"],
    ["CP-DR",[],"N+T","Deep Research scope"],
    ["CP-DR",[],"N+T","Deep Research findings and implications"],
    ["CP-DR",[],"T","Deep Research evidence / counterevidence"],
    ["CP-DR",[],"T","Deep Research evidence / counterevidence"],
    ["CP-DR",[],"N+T","Deep Research unresolved questions"],
    ["CP-DR",[],"T","Evidence / QA"],
    ["CP-L10",["TL10.1","TL20.1","TL23.1","TL30.1","TL40.1"],"N+T","Screening summary"],
    ["CP-L10",["TL10.2","TL20.2","TL23.2","TL30.2","TL40.2"],"N+T","Screening summary and implications"],
    ["CP-L10",["TL10.3","TL20.3","TL23.3","TL30.3","TL40.3"],"N+T","Screening implications"],
    ["CP-L10",["TL10.4","TL20.4","TL23.4","TL30.4","TL40.4"],"N+T","Screening upgrade gaps"],
]
