"""Versioned corpus manifests and answer-key attestation (DECISIONS §14.20).

One directory per pack under ``packs/``: ``manifest.json`` (what the pack is,
where every byte comes from, its SHA-256, document type, period, supersession,
disposition, licence class, the cells it applies to and the answer-key
attestation) and ``answer_key.json`` (expected facts, conflicts, forbidden
conclusions, per-cell route expectation and scoring bounds).

Bytes never live in the manifest. Three byte sources:

* ``synthetic`` — regenerated by ``synthetic.py`` and digest-checked;
* ``fetch`` — retained under ``caos/tests/corpus/documents`` by ``fetch.sh``
  (the Carnival pack; ``sources.txt`` stays the byte manifest CI caches on);
* ``external`` — supplied outside the repository under
  ``$CAOS_CORPUS_EXTERNAL_DIR/<pack>/`` (licensed marks, the stressed pack, the
  research pack). A null digest is an unacquired byte and fails closed.

An answer key is signed by attestation: the manifest carries the key file's
SHA-256 and one or more approvals ``{scope, reviewer, approved_at}``. A
host-control binding accepts ``host_control`` or ``analyst`` scope; a live
binding accepts ``analyst`` only. No approval, a stale digest, or a scope
below the binding's is a typed refusal, never a skip.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

CORPUS = Path(__file__).resolve().parent
PACKS = CORPUS / "packs"
RETAINED = CORPUS / "documents"
SOURCES = CORPUS / "sources.txt"
EXTERNAL_ENV = "CAOS_CORPUS_EXTERNAL_DIR"

MANIFEST_SCHEMA = "caos.corpus-pack.v1"
ANSWER_KEY_SCHEMA = "caos.answer-key.v1"
PACK_IDS = tuple(f"C{index:02d}" for index in range(1, 23))
PATHWAYS = ("FULL_CREDIT", "EARNINGS_UPDATE", "COVENANT_REFINANCING", "RELATIVE_VALUE",
            "DISTRESSED_RESTRUCTURING", "DEEP_RESEARCH")
DEPTHS = ("screen", "full")
LICENCE_CLASSES = ("issuer-public", "synthetic", "licensed-third-party", "analyst-authored")
BYTE_SOURCES = ("synthetic", "fetch", "external")
DISPOSITIONS = ("used", "superseded", "conflicting", "out_of_scope", "insufficient", "duplicate")
ROLES = ("relevant", "irrelevant", "conflicting", "superseded", "subsequent", "insufficient", "duplicate", "hostile", "invalid")
SUPERSESSION = ("current", "superseded", "restated", "amendment", "duplicate", "subsequent")
OUTCOMES = ("succeeded", "refused", "ingest")
KINDS = ("positive", "negative")
STAGES = ("run", "ingest")
SCOPES = ("host_control", "analyst")
_SHA256 = re.compile(r"^[0-9a-f]{64}$")
_DATE = re.compile(r"^\d{4}-\d{2}-\d{2}$")
_MANIFEST_KEYS = {
    "schema_version", "pack_id", "version", "title", "purpose", "kind", "stage", "issuer",
    "licence_class", "provenance", "bytes", "documents", "documents_from", "applies_to", "answer_key",
}
_DOCUMENT_KEYS = {
    "filename", "sha256", "media_type", "document_type", "period", "supersession", "provenance",
    "disposition", "analytical_role", "reason",
}


class CorpusError(Exception):
    """Typed corpus refusal; ``code`` is what the harness reports and exits on."""

    def __init__(self, code: str, detail: str) -> None:
        self.code = code
        self.detail = detail
        super().__init__(f"{code}: {detail}")


def sha256(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def canonical(value: Any) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")


def _reject_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for key, value in pairs:
        if key in out:
            raise ValueError(f"duplicate key {key!r}")
        out[key] = value
    return out


def _read_json(path: Path, code: str) -> dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=_reject_duplicate_keys)
    except FileNotFoundError as exc:
        raise CorpusError(code, f"{path.relative_to(CORPUS.parent.parent.parent)} is missing") from exc
    except (json.JSONDecodeError, ValueError, UnicodeDecodeError) as exc:
        raise CorpusError(code, f"{path.name} is malformed: {type(exc).__name__}") from exc


def pack_dir(pack_id: str) -> Path:
    if pack_id not in PACK_IDS:
        raise CorpusError("CORPUS_PACK_UNKNOWN", f"{pack_id} is not one of C01–C22")
    return PACKS / pack_id


def load_manifest(pack_id: str) -> dict[str, Any]:
    manifest = _read_json(pack_dir(pack_id) / "manifest.json", "CORPUS_MANIFEST_MISSING")
    validate_manifest(manifest, pack_id)
    return manifest


def load_answer_key(pack_id: str) -> tuple[dict[str, Any], bytes]:
    manifest = load_manifest(pack_id)
    path = pack_dir(pack_id) / manifest["answer_key"]["file"]
    try:
        raw = path.read_bytes()
    except FileNotFoundError as exc:
        raise CorpusError("ANSWER_KEY_MISSING", f"{pack_id}: {path.name} is missing") from exc
    try:
        key = json.loads(raw.decode("utf-8"), object_pairs_hook=_reject_duplicate_keys)
    except (json.JSONDecodeError, ValueError, UnicodeDecodeError) as exc:
        raise CorpusError("ANSWER_KEY_MALFORMED", f"{pack_id}: {type(exc).__name__}") from exc
    validate_answer_key(key, manifest)
    return key, raw


def _require(condition: bool, code: str, detail: str) -> None:
    if not condition:
        raise CorpusError(code, detail)


def validate_manifest(manifest: dict[str, Any], pack_id: str) -> None:
    code = "CORPUS_MANIFEST_INVALID"
    _require(isinstance(manifest, dict) and set(manifest) == _MANIFEST_KEYS, code,
             f"{pack_id}: manifest keys are not exact")
    _require(manifest["schema_version"] == MANIFEST_SCHEMA, code, f"{pack_id}: schema_version")
    _require(manifest["pack_id"] == pack_id, code, f"{pack_id}: pack_id mismatch")
    _require(isinstance(manifest["version"], str) and bool(manifest["version"]), code, f"{pack_id}: version")
    _require(manifest["kind"] in KINDS and manifest["stage"] in STAGES, code, f"{pack_id}: kind/stage")
    _require(manifest["licence_class"] in LICENCE_CLASSES, code, f"{pack_id}: licence_class")
    _require(isinstance(manifest["provenance"], str) and bool(manifest["provenance"]), code, f"{pack_id}: provenance")
    source = manifest["bytes"]
    _require(isinstance(source, dict) and set(source) == {"source", "location", "owner", "artifact"}, code,
             f"{pack_id}: bytes keys")
    _require(source["source"] in BYTE_SOURCES, code, f"{pack_id}: bytes.source")
    if source["source"] == "external":
        _require(bool(source["owner"]) and bool(source["artifact"]), code,
                 f"{pack_id}: an external pack names its owner and the artifact needed")
    documents = manifest["documents"]
    _require(isinstance(documents, list), code, f"{pack_id}: documents")
    if manifest["documents_from"] is not None:
        _require(manifest["documents_from"] in PACK_IDS and manifest["documents_from"] != pack_id, code,
                 f"{pack_id}: documents_from")
    else:
        _require(bool(documents), code, f"{pack_id}: a pack describes at least one document")
    names: set[str] = set()
    for document in documents:
        _require(isinstance(document, dict) and set(document) == _DOCUMENT_KEYS, code,
                 f"{pack_id}: document keys are not exact")
        _require(isinstance(document["filename"], str) and document["filename"] not in names, code,
                 f"{pack_id}: duplicate or invalid filename {document.get('filename')!r}")
        names.add(document["filename"])
        digest = document["sha256"]
        _require(digest is None or (isinstance(digest, str) and _SHA256.fullmatch(digest) is not None), code,
                 f"{pack_id}: {document['filename']} sha256")
        if source["source"] != "external":
            _require(digest is not None, code, f"{pack_id}: {document['filename']} has no pinned digest")
        _require(document["disposition"] in DISPOSITIONS, code, f"{pack_id}: {document['filename']} disposition")
        _require(document["analytical_role"] in ROLES, code, f"{pack_id}: {document['filename']} analytical_role")
        _require(document["supersession"] in SUPERSESSION, code, f"{pack_id}: {document['filename']} supersession")
        for field in ("media_type", "document_type", "provenance", "reason"):
            _require(isinstance(document[field], str) and bool(document[field]), code,
                     f"{pack_id}: {document['filename']} {field}")
        _require(document["period"] is None or isinstance(document["period"], str), code,
                 f"{pack_id}: {document['filename']} period")
    applies = manifest["applies_to"]
    _require(isinstance(applies, list) and bool(applies), code, f"{pack_id}: applies_to")
    seen: set[tuple[str, str]] = set()
    for cell in applies:
        _require(isinstance(cell, dict) and set(cell) == {"pathway", "depth", "outcome", "proves_pathway"}, code,
                 f"{pack_id}: applies_to keys")
        _require(cell["pathway"] in PATHWAYS and cell["depth"] in DEPTHS and cell["outcome"] in OUTCOMES, code,
                 f"{pack_id}: applies_to cell")
        _require(isinstance(cell["proves_pathway"], bool), code, f"{pack_id}: proves_pathway")
        _require((cell["pathway"], cell["depth"]) not in seen, code, f"{pack_id}: duplicate applies_to cell")
        seen.add((cell["pathway"], cell["depth"]))
        if cell["proves_pathway"]:
            _require(manifest["kind"] == "positive" and cell["outcome"] == "succeeded", code,
                     f"{pack_id}: only a positive pack whose expected outcome is success proves a pathway")
        _require((cell["outcome"] == "ingest") == (manifest["stage"] == "ingest"), code,
                 f"{pack_id}: an ingest-stage pack declares ingest outcomes and nothing else does")
    key = manifest["answer_key"]
    _require(isinstance(key, dict) and set(key) == {"file", "version", "sha256", "approvals"}, code,
             f"{pack_id}: answer_key keys")
    _require(isinstance(key["file"], str) and key["file"].endswith(".json") and "/" not in key["file"], code,
             f"{pack_id}: answer_key.file")
    _require(key["sha256"] is None or _SHA256.fullmatch(str(key["sha256"])) is not None, code,
             f"{pack_id}: answer_key.sha256")
    _require(isinstance(key["approvals"], list), code, f"{pack_id}: approvals")
    for approval in key["approvals"]:
        _require(isinstance(approval, dict) and set(approval) == {"scope", "reviewer", "approved_at", "note"}, code,
                 f"{pack_id}: approval keys")
        _require(approval["scope"] in SCOPES and isinstance(approval["reviewer"], str) and bool(approval["reviewer"]),
                 code, f"{pack_id}: approval scope/reviewer")
        _require(isinstance(approval["approved_at"], str) and _DATE.fullmatch(approval["approved_at"]) is not None,
                 code, f"{pack_id}: approved_at")


def validate_answer_key(key: dict[str, Any], manifest: dict[str, Any]) -> None:
    code = "ANSWER_KEY_INVALID"
    pack_id = manifest["pack_id"]
    _require(isinstance(key, dict) and key.get("schema_version") == ANSWER_KEY_SCHEMA, code, f"{pack_id}: schema")
    _require(key.get("pack_id") == pack_id, code, f"{pack_id}: answer key pack_id")
    _require(key.get("version") == manifest["answer_key"]["version"], code,
             f"{pack_id}: answer key version differs from the manifest")
    cells = key.get("cells")
    _require(isinstance(cells, dict), code, f"{pack_id}: cells")
    expected_cells = {f"{cell['pathway']}/{cell['depth']}": cell for cell in manifest["applies_to"]}
    _require(set(cells) == set(expected_cells), code,
             f"{pack_id}: answer key cells {sorted(cells)} differ from applies_to {sorted(expected_cells)}")
    for cell_id, cell in cells.items():
        _require(isinstance(cell, dict) and cell.get("outcome") == expected_cells[cell_id]["outcome"], code,
                 f"{pack_id}: {cell_id} outcome differs from the manifest")
        _require(cell.get("proves_pathway") == expected_cells[cell_id]["proves_pathway"], code,
                 f"{pack_id}: {cell_id} proves_pathway differs from the manifest")
        if cell["outcome"] == "refused":
            _require(isinstance(cell.get("refusal_code"), str) and bool(cell["refusal_code"]), code,
                     f"{pack_id}: {cell_id} a refusal cell names its typed code")
    for field in ("expected_facts", "conflicts", "forbidden_conclusions"):
        _require(isinstance(key.get(field), list), code, f"{pack_id}: {field}")
    for fact in key["expected_facts"]:
        _require({"id", "statement", "source", "match", "required"} <= set(fact), code, f"{pack_id}: fact keys")
        _require(isinstance(fact["match"], list) and all(isinstance(item, str) and item for item in fact["match"]),
                 code, f"{pack_id}: fact {fact.get('id')} match")
    for conflict in key["conflicts"]:
        _require({"id", "description", "match"} <= set(conflict), code, f"{pack_id}: conflict keys")
    for forbidden in key["forbidden_conclusions"]:
        _require({"id", "description", "match"} <= set(forbidden), code, f"{pack_id}: forbidden keys")
    if manifest["stage"] == "ingest":
        _require(isinstance(key.get("ingest_steps"), list) and bool(key["ingest_steps"]), code,
                 f"{pack_id}: an ingest-stage pack lists its ingest steps")


@dataclass(frozen=True)
class ResolvedDocument:
    filename: str
    content: bytes
    media_type: str
    sha256: str
    manifest_row: dict[str, Any]


def document_rows(manifest: dict[str, Any]) -> list[dict[str, Any]]:
    """The pack's document rows: the borrowed pack's rows (one hop) followed
    by the pack's own, so a pack composes "that pack plus these documents"."""
    rows: list[dict[str, Any]] = []
    if manifest["documents_from"] is not None:
        rows.extend(load_manifest(manifest["documents_from"])["documents"])
    rows.extend(manifest["documents"])
    return rows


def _external_dir() -> Path | None:
    value = os.environ.get(EXTERNAL_ENV, "").strip()
    return Path(value) if value else None


def _resolve_owned(owner: dict[str, Any]) -> list[ResolvedDocument]:
    source = owner["bytes"]
    pack_id = owner["pack_id"]
    rows = list(owner["documents"])
    generated: dict[str, tuple[bytes, str]] = {}
    if source["source"] == "synthetic":
        from corpus.synthetic import build

        generated = {name: (content, media_type) for name, content, media_type in build(pack_id)}
        unexpected = set(generated) - {row["filename"] for row in rows}
        missing = {row["filename"] for row in rows} - set(generated)
        _require(not unexpected and not missing, "CORPUS_MANIFEST_INVALID",
                 f"{pack_id}: synthetic builder and manifest disagree (extra {sorted(unexpected)}, missing {sorted(missing)})")
    resolved: list[ResolvedDocument] = []
    for row in rows:
        pinned = row["sha256"]
        _require_pinned(owner, row)
        if source["source"] == "synthetic":
            content, media_type = generated[row["filename"]]
        else:
            if source["source"] == "fetch":
                path = CORPUS.parent.parent.parent / source["location"] / row["filename"]
            else:
                base = _external_dir()
                if base is None:
                    raise CorpusError("CORPUS_BYTES_MISSING",
                                      f"{pack_id}: {EXTERNAL_ENV} is not set; external pack bytes cannot be located")
                path = base / pack_id / row["filename"]
            try:
                content = path.read_bytes()
            except FileNotFoundError as exc:
                raise CorpusError("CORPUS_BYTES_MISSING", f"{pack_id}/{row['filename']}: not retained at {path}") from exc
            media_type = row["media_type"]
        digest = sha256(content)
        if digest != pinned:
            raise CorpusError("CORPUS_DIGEST_MISMATCH", f"{pack_id}/{row['filename']}: {digest} != pinned {pinned}")
        resolved.append(ResolvedDocument(row["filename"], content, media_type, digest, row))
    return resolved


def _require_pinned(owner: dict[str, Any], row: dict[str, Any]) -> None:
    if row["sha256"] is None:
        source = owner["bytes"]
        raise CorpusError(
            "CORPUS_BYTES_UNACQUIRED",
            f"{owner['pack_id']}/{row['filename']}: no pinned digest — BLOCKED EXTERNAL, "
            f"owner {source['owner']}, needs {source['artifact']}",
        )


def resolve_documents(manifest: dict[str, Any]) -> list[ResolvedDocument]:
    """Every byte of the pack (borrowed rows first), digest-verified. Raises a
    typed CorpusError when a byte is unacquired, missing, or does not match
    its pin — never skips. An unpinned digest is a fact about the manifest, so
    it is refused before any byte is read: the external input the pack still
    lacks names itself whether or not the borrowed pack's bytes are present on
    this machine (the 3.12 CI leg carries no corpus)."""
    owners: list[dict[str, Any]] = []
    if manifest["documents_from"] is not None:
        owners.append(load_manifest(manifest["documents_from"]))
    if manifest["documents"]:
        owners.append(manifest)
    for owner in owners:
        for row in owner["documents"]:
            _require_pinned(owner, row)
    resolved: list[ResolvedDocument] = []
    for owner in owners:
        resolved.extend(_resolve_owned(owner))
    return resolved


def attest_answer_key(manifest: dict[str, Any], raw_key: bytes, binding_kind: str) -> dict[str, Any]:
    """The approval that licenses this binding kind to score against the key."""
    pack_id = manifest["pack_id"]
    record = manifest["answer_key"]
    if record["sha256"] is None or not record["approvals"]:
        raise CorpusError("ANSWER_KEY_UNSIGNED", f"{pack_id}: the answer key carries no attestation")
    digest = sha256(raw_key)
    if digest != record["sha256"]:
        raise CorpusError("ANSWER_KEY_DIGEST_MISMATCH", f"{pack_id}: answer key digest {digest} != attested {record['sha256']}")
    accepted = ("analyst",) if binding_kind == "live" else SCOPES
    for approval in record["approvals"]:
        if approval["scope"] in accepted:
            return approval
    raise CorpusError("ANSWER_KEY_SCOPE_INSUFFICIENT",
                      f"{pack_id}: a {binding_kind} binding needs an approval in {accepted}; found "
                      f"{sorted(approval['scope'] for approval in record['approvals'])}")


def manifest_digest(pack_id: str) -> str:
    return sha256((pack_dir(pack_id) / "manifest.json").read_bytes())


def corpus_digest(pack_ids: tuple[str, ...] = PACK_IDS) -> str:
    """One digest over every manifest, answer key and pinned document digest:
    what a qualification result binds to (MOD-023)."""
    view: dict[str, Any] = {}
    for pack_id in pack_ids:
        manifest = load_manifest(pack_id)
        key_path = pack_dir(pack_id) / manifest["answer_key"]["file"]
        view[pack_id] = {
            "manifest": manifest_digest(pack_id),
            "answer_key": sha256(key_path.read_bytes()) if key_path.is_file() else None,
            "documents": {row["filename"]: row["sha256"] for row in document_rows(manifest)},
        }
    return sha256(canonical(view))


def source_rows() -> list[tuple[str, str, str, str, str]]:
    rows = []
    for line in SOURCES.read_text(encoding="utf-8").splitlines():
        if line.strip() and not line.lstrip().startswith("#"):
            name, digest, document_type, period, url = line.split()
            rows.append((name, digest, document_type, period, url))
    return rows


def pin(pack_id: str, *, reviewer: str, approved_at: str) -> dict[str, Any]:
    """Re-pin a pack's synthetic document digests and its answer-key digest
    under a host-control attestation. Refuses to touch an analyst-approved key
    whose bytes changed: the analyst re-approves, the tool never does."""
    path = pack_dir(pack_id) / "manifest.json"
    manifest = _read_json(path, "CORPUS_MANIFEST_MISSING")
    if manifest["bytes"]["source"] == "synthetic" and manifest["documents"]:
        from corpus.synthetic import build

        digests = {name: sha256(content) for name, content, _media in build(pack_id)}
        for row in manifest["documents"]:
            row["sha256"] = digests[row["filename"]]
    key_path = pack_dir(pack_id) / manifest["answer_key"]["file"]
    digest = sha256(key_path.read_bytes())
    record = manifest["answer_key"]
    if record["sha256"] != digest:
        if any(approval["scope"] == "analyst" for approval in record["approvals"]):
            raise CorpusError("ANSWER_KEY_ANALYST_REAPPROVAL_REQUIRED",
                              f"{pack_id}: the answer key changed under an analyst approval")
        record["sha256"] = digest
        record["approvals"] = [approval for approval in record["approvals"] if approval["scope"] != "host_control"]
        record["approvals"].append({
            "scope": "host_control", "reviewer": reviewer, "approved_at": approved_at,
            "note": "host-control attestation of the draft key: orchestration proof only, never analysis",
        })
    validate_manifest(manifest, pack_id)
    path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    return manifest
